In [1]:
#load dataset
import pandas as pd
data = pd.read_csv('IMDB Dataset.csv')

In [2]:
data.head(10)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
5  Probably my all-time favorite movie, a story o...  positive
6  I sure would like to see a resurrection of a u...  positive
7  This show was an amazing, fresh & innovative i...  negative
8  Encouraged by the positive comments about this...  negative
9  If you like original gut wrenching laughter yo...  positive

TRANSFORMING DOC INTO FEATURE VECTORS

In [3]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
doc = np.array(['The sun is shining',
                 'The weather is sweet',
                 'The sun is shining, the weather is sweet, and one and one is two'])
bag = count.fit_transform(doc)
print(count.vocabulary_)
                

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [4]:
print(bag)

  (0, 6)	1
  (0, 4)	1
  (0, 1)	1
  (0, 3)	1
  (1, 6)	1
  (1, 1)	1
  (1, 8)	1
  (1, 5)	1
  (2, 6)	2
  (2, 4)	1
  (2, 1)	3
  (2, 3)	1
  (2, 8)	1
  (2, 5)	1
  (2, 0)	2
  (2, 2)	2
  (2, 7)	1


In [5]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0]
 [0 1 0 0 0 1 1 0 1]
 [2 3 2 1 1 1 2 1 1]]


In [7]:
#task3
from sklearn.feature_extraction.text import TfidataTransformer

tfidata = TfidataTransformer(use_idata = True, norm = 'l2', smooth_idata = True)
print(tfidata.fit_transform(count.fit_transform(doc)).toarray())

[[0.         0.43370786 0.         0.55847784 0.55847784 0.
  0.43370786 0.         0.        ]
 [0.         0.43370786 0.         0.         0.         0.55847784
  0.43370786 0.         0.55847784]
 [0.50238645 0.44507629 0.50238645 0.19103892 0.19103892 0.19103892
  0.29671753 0.25119322 0.19103892]]


In [8]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

def stemmer_tokenize(text):
    return[porter.stem(word) for word in text.split()]
stemmer_tokenize('coders like coding and so they code')

['coder', 'like', 'code', 'and', 'so', 'they', 'code']

#TASK 6: VECTORISING THE DATA

In [13]:
from sklearn.feature_extraction.text import TfidataVectorizer
tfidata = TfidataVectorizer(strip_accents = None,
                       lowercase = False,
                       tokenizer = stemmer_tokenize,
                       use_idata = True,
                       norm='l2',
                       smooth_idata = True)
Y = data.sentiment.values
X = tfidata.fit_transform(data.review)

#TASK 7 DOCUMENT CLASSIFICATION USING LOGISTIC REGRESSION

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X, Y, random_state =1,
                                                  test_size = 0.5, shuffle = False)
import pickle
from sklearn.linear_model import LogisticRegressionCV
#model
clf = LogisticRegressionCV(cv = 5, scoring = 'accuracy', random_state = 1, n_jobs = -3, verbose = 3, max_iter = 300).fit(X_train,Y_train)

#saving model
saved_model = open('saved_model.sav' , 'wb')
pickle.dump(clf, saved_model)

[Parallel(n_jobs=-3)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=-3)]: Done   2 out of   5 | elapsed:  4.5min remaining:  6.7min
[Parallel(n_jobs=-3)]: Done   5 out of   5 | elapsed:  4.6min finished


#TASK 8:MODEL EVALUATION